seata:
  enabled: true
  application-id: account-server-name
  tx-service-group: my_test_group
  enableAutoDataSourceProxy: true

  use-jdk-proxy: false
  service:
    vgroup-mapping:
      #这里的 my_test_group  要和 application.yml 相对应 【alibaba:seata:tx-service-group: my_test_group 】
      my_test_group: seata-server  # 这里 seata-server  指的是 seata-server 服务器注册到eureka的名字
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: file
  registry:
    type: eureka
    eureka:
      weight: 1
      service-url: http://localhost:8761/eureka
