seata:
  enabled: true
  application-id: multiple-datasources-name
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: false

  use-jdk-proxy: false
  service:
    vgroup-mapping:
      my_test_tx_group: seata-server
    enable-degrade: false
    disable-global-transaction: false
    grouplist:
      seata-server: 127.0.0.1:8091
  config:
    type: file
  registry:
    type: file
